// Generated by CoffeeScript 1.6.2
(function() {
  var getPossibleWords, t9App;

  t9App = angular.module('t9App', []);

  t9App.controller('T9Controller', function($scope, $http) {
    $scope.input = "";
    $scope.maxInputLength = 10;
    $http.get('data.json').success(function(data) {
      $scope.words = data.words;
      $scope.keys = data.keys;
      return $scope.suggestions = ['a', 'b', 'c'];
    });
    $scope.keydown = function(e) {
      if (e.keyCode === 8) {
        e.preventDefault();
        return $scope.input = $scope.input.slice(0, $scope.input.length - 1);
      }
    };
    $scope.keypress = function(e) {
      if (e.keyCode >= 48 && e.keyCode <= 57) {
        e.preventDefault();
        return $scope.input += (e.keyCode - 48).toString();
      }
    };
    $scope.dial = function(numPressed) {
      return $scope.input += numPressed;
    };
    return $scope.$watch('input', function(current, old) {
      $scope.input = $scope.input.replace(/[\D]/gi, '');
      if ($scope.input.length > $scope.maxInputLength) {
        return $scope.input = $scope.input.slice(0, $scope.maxInputLength);
      }
    });
  });

  getPossibleWords = function(numberSequence) {
    if (typeof numberSequence === 'number') {
      numberSequence = numberSequence.toString();
    }
    numberSequence = numberSequence.replace(/[01]/g, '');
    numberSequence = numberSequence.split('');
    return numberSequence;
  };

}).call(this);
